name: Regression Test

on:
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "!src/analysis/**"
      - "pyproject.toml"
      - ".github/workflows/regression_test.yaml"

jobs:
  regression-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Conda environment
        run: |
          eval "$(conda shell.bash hook)"
          conda activate /home/xj265/anaconda3/envs/tabstruct

      - name: Run tests
        run: |
          pytest tests/
